#!/usr/bin/env python3
# ==============================================================
#  Module: constants
#  Project: pige.ovpn TUI
#  Description: Stores all stable variables, constants, and
#               configuration paths used across the project.
# ==============================================================

import os
from pathlib import Path
import json

from pigeovpn.__about__ import __title__, __url__
# --------------------------------------------------------------
# General Application Information
# --------------------------------------------------------------
APP_NAME: str = __title__
GITHUB_REPO = __url__

# --------------------------------------------------------------
# Directory and File Paths
# --------------------------------------------------------------
JSON_CONF = os.path.join(os.path.dirname(__file__), 'conf.json')

def get_real_home() -> Path:
    # If running with sudo, load the invoking user's home dir
    if os.geteuid() == 0 and "SUDO_USER" in os.environ:
        return Path("/home") / os.environ["SUDO_USER"]
    else:
        return Path.home()

HOME_DIRECTORY = get_real_home()

# Read the directory where the .ovpn configurations are stored (given by the user)
def get_ovpnFilesDir() -> None:
    with open(JSON_CONF, "r") as file:
        config = json.load(file)

    return Path(config["ovpn_directory"])
OVPN_FILES_DIR = get_ovpnFilesDir()

CREDS_FILE = "/etc/openvpn/credentials.txt" # Where credentials are stored


# --------------------------------------------------------------
# Terminals
# --------------------------------------------------------------
"""
Sudo commands are run in new terminal windows, where the user has to insert the sudo password. 
The app checks the most common terminal applications for linux and its flag for running commands.
"""
current_dir = Path(__file__).parent.resolve()
COMMON_TERMINALS = {
        'gnome-terminal': '--',
        'konsole': '-e', 
        'x-terminal-emulator': '-e',
        'xfce4-terminal': '-e',
        'alacritty': '-e',
        'terminator': '-e',
        'kitty': 'launch',
        'mate-terminal': '-e',
        }

# --------------------------------------------------------------
# Modules's parameters
# --------------------------------------------------------------
IP_REFRESH_INTERVAL = 30  # seconds, used for the background thread to fetch the ip info (connection_manager.py)
UPDATE_DELAY = 1.0 # seconds, used for the download and upload speed as well as for the graph

# Initiate the upload & download speed and usage
upload_usage, download_usage, upload_speed, download_speed = "", "", "", ""

ASCII_art = r"""
         _                                   
   _ __ (_) __ _  ___  _____   ___ __  _ __  
  | '_ \| |/ _` |/ _ \/ _ \ \ / / '_ \| '_ \ 
  | |_) | | (_| |  __/ (_) \ V /| |_) | | | |
  | .__/|_|\__, |\___|\___/ \_/ | .__/|_| |_|
  |_|      |___/                |_|          
"""

# --------------------------------------------------------------
# Flags' directory
# --------------------------------------------------------------
flags_directory = {
    "Afghanistan": "🇦🇫",
    "Albania": "🇦🇱",
    "Algeria": "🇩🇿",
    "Andorra": "🇦🇩",
    "Angola": "🇦🇴",
    "Argentina": "🇦🇷",
    "Armenia": "🇦🇲",
    "Australia": "🇦🇺",
    "Austria": "🇦🇹",
    "Azerbaijan": "🇦🇿",
    "Bahamas": "🇧🇸",
    "Bahrain": "🇧🇭",
    "Bangladesh": "🇧🇩",
    "Belarus": "🇧🇾",
    "Belgium": "🇧🇪",
    "Belize": "🇧🇿",
    "Benin": "🇧🇯",
    "Bolivia": "🇧🇴",
    "Bosnia and Herzegovina": "🇧🇦",
    "Botswana": "🇧🇼",
    "Brazil": "🇧🇷",
    "Brunei": "🇧🇳",
    "Bulgaria": "🇧🇬",
    "Burkina Faso": "🇧🇫",
    "Burundi": "🇧🇮",
    "Cambodia": "🇰🇭",
    "Cameroon": "🇨🇲",
    "Canada": "🇨🇦",
    "Cape Verde": "🇨🇻",
    "Central African Republic": "🇨🇫",
    "Chad": "🇹🇩",
    "Chile": "🇨🇱",
    "China": "🇨🇳",
    "Colombia": "🇨🇴",
    "Congo (DRC)": "🇨🇩",
    "Congo (Republic)": "🇨🇬",
    "Costa Rica": "🇨🇷",
    "Croatia": "🇭🇷",
    "Cuba": "🇨🇺",
    "Cyprus": "🇨🇾",
    "Czech Republic": "🇨🇿",
    "Denmark": "🇩🇰",
    "Dominican Republic": "🇩🇴",
    "Ecuador": "🇪🇨",
    "Egypt": "🇪🇬",
    "El Salvador": "🇸🇻",
    "Estonia": "🇪🇪",
    "Ethiopia": "🇪🇹",
    "Finland": "🇫🇮",
    "France": "🇫🇷",
    "Georgia": "🇬🇪",
    "Germany": "🇩🇪",
    "Ghana": "🇬🇭",
    "Greece": "🇬🇷",
    "Guatemala": "🇬🇹",
    "Haiti": "🇭🇹",
    "Honduras": "🇭🇳",
    "Hungary": "🇭🇺",
    "Iceland": "🇮🇸",
    "India": "🇮🇳",
    "Indonesia": "🇮🇩",
    "Iran": "🇮🇷",
    "Iraq": "🇮🇶",
    "Ireland": "🇮🇪",
    "Israel": "🇮🇱",
    "Italy": "🇮🇹",
    "Jamaica": "🇯🇲",
    "Japan": "🇯🇵",
    "Jordan": "🇯🇴",
    "Kazakhstan": "🇰🇿",
    "Kenya": "🇰🇪",
    "Kuwait": "🇰🇼",
    "Kyrgyzstan": "🇰🇬",
    "Laos": "🇱🇦",
    "Latvia": "🇱🇻",
    "Lebanon": "🇱🇧",
    "Libya": "🇱🇾",
    "Liechtenstein": "🇱🇮",
    "Lithuania": "🇱🇹",
    "Luxembourg": "🇱🇺",
    "Madagascar": "🇲🇬",
    "Malawi": "🇲🇼",
    "Malaysia": "🇲🇾",
    "Mali": "🇲🇱",
    "Malta": "🇲🇹",
    "Mexico": "🇲🇽",
    "Moldova": "🇲🇩",
    "Monaco": "🇲🇨",
    "Mongolia": "🇲🇳",
    "Montenegro": "🇲🇪",
    "Morocco": "🇲🇦",
    "Mozambique": "🇲🇿",
    "Namibia": "🇳🇦",
    "Nepal": "🇳🇵",
    "Netherlands": "🇳🇱",
    "The Netherlands": "🇳🇱",
    "New Zealand": "🇳🇿",
    "Nicaragua": "🇳🇮",
    "Niger": "🇳🇪",
    "Nigeria": "🇳🇬",
    "North Macedonia": "🇲🇰",
    "Norway": "🇳🇴",
    "Oman": "🇴🇲",
    "Pakistan": "🇵🇰",
    "Panama": "🇵🇦",
    "Paraguay": "🇵🇾",
    "Peru": "🇵🇪",
    "Philippines": "🇵🇭",
    "Poland": "🇵🇱",
    "Portugal": "🇵🇹",
    "Qatar": "🇶🇦",
    "Romania": "🇷🇴",
    "Russia": "🇷🇺",
    "Rwanda": "🇷🇼",
    "Saudi Arabia": "🇸🇦",
    "Senegal": "🇸🇳",
    "Serbia": "🇷🇸",
    "Singapore": "🇸🇬",
    "Slovakia": "🇸🇰",
    "Slovenia": "🇸🇮",
    "Somalia": "🇸🇴",
    "South Africa": "🇿🇦",
    "South Korea": "🇰🇷",
    "Spain": "🇪🇸",
    "Sri Lanka": "🇱🇰",
    "Sweden": "🇸🇪",
    "Switzerland": "🇨🇭",
    "Syria": "🇸🇾",
    "Taiwan": "🇹🇼",
    "Tajikistan": "🇹🇯",
    "Tanzania": "🇹🇿",
    "Thailand": "🇹🇭",
    "Tunisia": "🇹🇳",
    "Turkey": "🇹🇷",
    "Uganda": "🇺🇬",
    "Ukraine": "🇺🇦",
    "United Arab Emirates": "🇦🇪",
    "United Kingdom": "🇬🇧",
    "United States": "🇺🇸",
    "United States of America": "🇺🇸",
    "USA": "🇺🇸",
    "U.S.A.": "🇺🇸",
    "Uruguay": "🇺🇾",
    "Uzbekistan": "🇺🇿",
    "Venezuela": "🇻🇪",
    "Vietnam": "🇻🇳",
    "Yemen": "🇾🇪",
    "Zambia": "🇿🇲",
    "Zimbabwe": "🇿🇼",
}

country_flags = {
    "AF": "🇦🇫",
    "AL": "🇦🇱",
    "DZ": "🇩🇿",
    "AD": "🇦🇩",
    "AO": "🇦🇴",
    "AR": "🇦🇷",
    "AM": "🇦🇲",
    "AU": "🇦🇺",
    "AT": "🇦🇹",
    "AZ": "🇦🇿",
    "BS": "🇧🇸",
    "BH": "🇧🇭",
    "BD": "🇧🇩",
    "BB": "🇧🇧",
    "BY": "🇧🇾",
    "BE": "🇧🇪",
    "BZ": "🇧🇿",
    "BJ": "🇧🇯",
    "BT": "🇧🇹",
    "BO": "🇧🇴",
    "BA": "🇧🇦",
    "BW": "🇧🇼",
    "BR": "🇧🇷",
    "BN": "🇧🇳",
    "BG": "🇧🇬",
    "BF": "🇧🇫",
    "BI": "🇧🇮",
    "KH": "🇰🇭",
    "CM": "🇨🇲",
    "CA": "🇨🇦",
    "CV": "🇨🇻",
    "CF": "🇨🇫",
    "TD": "🇹🇩",
    "CL": "🇨🇱",
    "CN": "🇨🇳",
    "CO": "🇨🇴",
    "KM": "🇰🇲",
    "CD": "🇨🇩",
    "CG": "🇨🇬",
    "CR": "🇨🇷",
    "HR": "🇭🇷",
    "CU": "🇨🇺",
    "CY": "🇨🇾",
    "CZ": "🇨🇿",
    "DK": "🇩🇰",
    "DJ": "🇩🇯",
    "DO": "🇩🇴",
    "DM": "🇩🇲",
    "EC": "🇪🇨",
    "EG": "🇪🇬",
    "SV": "🇸🇻",
    "GQ": "🇬🇶",
    "ER": "🇪🇷",
    "EE": "🇪🇪",
    "ET": "🇪🇹",
    "FI": "🇫🇮",
    "FR": "🇫🇷",
    "GA": "🇬🇦",
    "GM": "🇬🇲",
    "GE": "🇬🇪",
    "DE": "🇩🇪",
    "GH": "🇬🇭",
    "GR": "🇬🇷",
    "GD": "🇬🇩",
    "GT": "🇬🇹",
    "GN": "🇬🇳",
    "GW": "🇬🇼",
    "GY": "🇬🇾",
    "HT": "🇭🇹",
    "HN": "🇭🇳",
    "HU": "🇭🇺",
    "IS": "🇮🇸",
    "IN": "🇮🇳",
    "ID": "🇮🇩",
    "IR": "🇮🇷",
    "IQ": "🇮🇶",
    "IE": "🇮🇪",
    "IL": "🇮🇱",
    "IT": "🇮🇹",
    "JM": "🇯🇲",
    "JP": "🇯🇵",
    "JO": "🇯🇴",
    "KZ": "🇰🇿",
    "KE": "🇰🇪",
    "KI": "🇰🇮",
    "KW": "🇰🇼",
    "KG": "🇰🇬",
    "LA": "🇱🇦",
    "LV": "🇱🇻",
    "LB": "🇱🇧",
    "LS": "🇱🇸",
    "LR": "🇱🇷",
    "LY": "🇱🇾",
    "LI": "🇱🇮",
    "LT": "🇱🇹",
    "LU": "🇱🇺",
    "MG": "🇲🇬",
    "MW": "🇲🇼",
    "MY": "🇲🇾",
    "MV": "🇲🇻",
    "ML": "🇲🇱",
    "MT": "🇲🇹",
    "MH": "🇲🇭",
    "MR": "🇲🇷",
    "MU": "🇲🇺",
    "MX": "🇲🇽",
    "FM": "🇫🇲",
    "MD": "🇲🇩",
    "MC": "🇲🇨",
    "MN": "🇲🇳",
    "ME": "🇲🇪",
    "MA": "🇲🇦",
    "MZ": "🇲🇿",
    "NA": "🇳🇦",
    "NR": "🇳🇷",
    "NP": "🇳🇵",
    "NL": "🇳🇱",
    "NZ": "🇳🇿",
    "NI": "🇳🇮",
    "NE": "🇳🇪",
    "NG": "🇳🇬",
    "NO": "🇳🇴",
    "MK": "🇲🇰",
    "OM": "🇴🇲",
    "PK": "🇵🇰",
    "PW": "🇵🇼",
    "PA": "🇵🇦",
    "PG": "🇵🇬",
    "PY": "🇵🇾",
    "PE": "🇵🇪",
    "PH": "🇵🇭",
    "PL": "🇵🇱",
    "PT": "🇵🇹",
    "QA": "🇶🇦",
    "RO": "🇷🇴",
    "RU": "🇷🇺",
    "RW": "🇷🇼",
    "KN": "🇰🇳",
    "LC": "🇱🇨",
    "VC": "🇻🇨",
    "WS": "🇼🇸",
    "SM": "🇸🇲",
    "ST": "🇸🇹",
    "SA": "🇸🇦",
    "SN": "🇸🇳",
    "RS": "🇷🇸",
    "SC": "🇸🇨",
    "SL": "🇸🇱",
    "SG": "🇸🇬",
    "SK": "🇸🇰",
    "SI": "🇸🇮",
    "SB": "🇸🇧",
    "SO": "🇸🇴",
    "ZA": "🇿🇦",
    "KR": "🇰🇷",
    "SS": "🇸🇸",
    "ES": "🇪🇸",
    "LK": "🇱🇰",
    "SD": "🇸🇩",
    "SR": "🇸🇷",
    "SE": "🇸🇪",
    "CH": "🇨🇭",
    "SY": "🇸🇾",
    "TW": "🇹🇼",
    "TJ": "🇹🇯",
    "TZ": "🇹🇿",
    "TH": "🇹🇭",
    "TL": "🇹🇱",
    "TG": "🇹🇬",
    "TO": "🇹🇴",
    "TT": "🇹🇹",
    "TN": "🇹🇳",
    "TR": "🇹🇷",
    "TM": "🇹🇲",
    "TV": "🇹🇻",
    "UG": "🇺🇬",
    "UA": "🇺🇦",
    "AE": "🇦🇪",
    "GB": "🇬🇧",
    "US": "🇺🇸",
    "UY": "🇺🇾",
    "UZ": "🇺🇿",
    "VU": "🇻🇺",
    "VA": "🇻🇦",
    "VE": "🇻🇪",
    "VN": "🇻🇳",
    "YE": "🇾🇪",
    "ZM": "🇿🇲",
    "ZW": "🇿🇼",
}
